---
apiVersion: v1
kind: Service
metadata:
  name: org1peer2
spec:
  selector:
    app: org1peer2
  ports:
  - protocol: TCP
    targetPort: 30210
    port: 30210
    name: grpc
  - protocol: TCP
    targetPort: 30211
    port: 30211
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org1peer2
  labels:
    app: org1peer2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org1peer2
  template:
    metadata:
      labels:
        app: org1peer2
    spec:
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: filepvc
      - name: dind-storage
        emptyDir: {}

      containers:
      - name: org1peer2
        image: hyperledger/fabric-peer:1.4.0
        command: ["sh", "-c", "sleep 1 && peer node start"]
        env:
        - name: TZ
          value: "Europe/Istanbul"
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: CORE_PEER_ID
          value: org1peer2
        - name: CORE_PEER_ADDRESS
          value: org1peer2:30210
        #- name: CORE_PEER_CHAINCODELISTENADDRESS
        #  value: "localhost:30210"
        #CORE_PEER_GOSSIP_EXTERNALENDPOINT for Hyperledger Explorer
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: org1peer2:30210
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:30210
        - name: CORE_PEER_EVENTS_ADDRESS
          value: 0.0.0.0:30211
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: org1peer2:30210
        - name: CORE_PEER_GOSSIP_ENDPOINT
          value: org1peer2:30210
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_VM_ENDPOINT
          value: "http://localhost:2375"
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/artifacts/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/
        - name: FABRIC_LOGGING_SPEC
          value: info
        - name: CORE_LOGGING_PEER
          value: info
        - name: CORE_LOGGING_CAUTHDSL
          value: info
        - name: CORE_LOGGING_GOSSIP
          value: info
        - name: CORE_LOGGING_LEDGER
          value: info
        - name: CORE_LOGGING_MSP
          value: info
        - name: CORE_LOGGING_POLICIES
          value: info
        - name: CORE_LOGGING_GRPC
          value: info
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: "admin"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: "admin"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: orderer:31010
        - name: GODEBUG
          value: "netdns=go"
        - name: CORE_VM_DOCKER_ATTACHSTDOUT
          value: "true"
        - name: CORE_CHAINCODE_BUILDER
          value: hyperledger/fabric-ccenv:1.4          
        volumeMounts:
        - mountPath: /shared
          name: myvolume
        ports:
        - containerPort: 30210
        - containerPort: 30211

      - name: couchdb
        image: hyperledger/fabric-couchdb:0.4.14
        env:
        - name: TZ
          value: "Europe/Istanbul"
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          value: "admin"

      - name: dind
        image: docker:18.05-dind
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
