apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
spec:
  tls:
  - hosts:
    - node-red.{{INGRESS-SUBDOMAIN}}.us-south.containers.appdomain.cloud
    secretName: {{INGRESS-SUBDOMAIN}}
  rules:
  - host: node-red.{{INGRESS-SUBDOMAIN}}.us-south.containers.appdomain.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: node-red
           port:
              number: 1880
